import type { Repo } from './types';

export const movieAppMock: Repo = {
  id: 293103208,
  node_id: 'MDEwOlJlcG9zaXRvcnkyOTMxMDMyMDg=',
  name: 'movie-app',
  full_name: 'zyderus/movie-app',
  private: false,
  owner: {
    login: 'zyderus',
    id: 70410634,
    node_id: 'MDQ6VXNlcjcwNDEwNjM0',
    avatar_url: 'https://avatars.githubusercontent.com/u/70410634?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/zyderus',
    html_url: 'https://github.com/zyderus',
    followers_url: 'https://api.github.com/users/zyderus/followers',
    following_url:
      'https://api.github.com/users/zyderus/following{/other_user}',
    gists_url: 'https://api.github.com/users/zyderus/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/zyderus/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/zyderus/subscriptions',
    organizations_url: 'https://api.github.com/users/zyderus/orgs',
    repos_url: 'https://api.github.com/users/zyderus/repos',
    events_url: 'https://api.github.com/users/zyderus/events{/privacy}',
    received_events_url: 'https://api.github.com/users/zyderus/received_events',
    type: 'User',
    site_admin: false,
  },
  html_url: 'https://github.com/zyderus/movie-app',
  description:
    'A movie information portal with intuitive UI and easily accesible relevant information',
  fork: false,
  url: 'https://api.github.com/repos/zyderus/movie-app',
  forks_url: 'https://api.github.com/repos/zyderus/movie-app/forks',
  keys_url: 'https://api.github.com/repos/zyderus/movie-app/keys{/key_id}',
  collaborators_url:
    'https://api.github.com/repos/zyderus/movie-app/collaborators{/collaborator}',
  teams_url: 'https://api.github.com/repos/zyderus/movie-app/teams',
  hooks_url: 'https://api.github.com/repos/zyderus/movie-app/hooks',
  issue_events_url:
    'https://api.github.com/repos/zyderus/movie-app/issues/events{/number}',
  events_url: 'https://api.github.com/repos/zyderus/movie-app/events',
  assignees_url:
    'https://api.github.com/repos/zyderus/movie-app/assignees{/user}',
  branches_url:
    'https://api.github.com/repos/zyderus/movie-app/branches{/branch}',
  tags_url: 'https://api.github.com/repos/zyderus/movie-app/tags',
  blobs_url: 'https://api.github.com/repos/zyderus/movie-app/git/blobs{/sha}',
  git_tags_url: 'https://api.github.com/repos/zyderus/movie-app/git/tags{/sha}',
  git_refs_url: 'https://api.github.com/repos/zyderus/movie-app/git/refs{/sha}',
  trees_url: 'https://api.github.com/repos/zyderus/movie-app/git/trees{/sha}',
  statuses_url: 'https://api.github.com/repos/zyderus/movie-app/statuses/{sha}',
  languages_url: 'https://api.github.com/repos/zyderus/movie-app/languages',
  stargazers_url: 'https://api.github.com/repos/zyderus/movie-app/stargazers',
  contributors_url:
    'https://api.github.com/repos/zyderus/movie-app/contributors',
  subscribers_url: 'https://api.github.com/repos/zyderus/movie-app/subscribers',
  subscription_url:
    'https://api.github.com/repos/zyderus/movie-app/subscription',
  commits_url: 'https://api.github.com/repos/zyderus/movie-app/commits{/sha}',
  git_commits_url:
    'https://api.github.com/repos/zyderus/movie-app/git/commits{/sha}',
  comments_url:
    'https://api.github.com/repos/zyderus/movie-app/comments{/number}',
  issue_comment_url:
    'https://api.github.com/repos/zyderus/movie-app/issues/comments{/number}',
  contents_url:
    'https://api.github.com/repos/zyderus/movie-app/contents/{+path}',
  compare_url:
    'https://api.github.com/repos/zyderus/movie-app/compare/{base}...{head}',
  merges_url: 'https://api.github.com/repos/zyderus/movie-app/merges',
  archive_url:
    'https://api.github.com/repos/zyderus/movie-app/{archive_format}{/ref}',
  downloads_url: 'https://api.github.com/repos/zyderus/movie-app/downloads',
  issues_url: 'https://api.github.com/repos/zyderus/movie-app/issues{/number}',
  pulls_url: 'https://api.github.com/repos/zyderus/movie-app/pulls{/number}',
  milestones_url:
    'https://api.github.com/repos/zyderus/movie-app/milestones{/number}',
  notifications_url:
    'https://api.github.com/repos/zyderus/movie-app/notifications{?since,all,participating}',
  labels_url: 'https://api.github.com/repos/zyderus/movie-app/labels{/name}',
  releases_url: 'https://api.github.com/repos/zyderus/movie-app/releases{/id}',
  deployments_url: 'https://api.github.com/repos/zyderus/movie-app/deployments',
  created_at: '2020-09-05T15:31:40Z',
  updated_at: '2024-06-12T21:39:44Z',
  pushed_at: '2021-08-06T13:16:56Z',
  git_url: 'git://github.com/zyderus/movie-app.git',
  ssh_url: 'git@github.com:zyderus/movie-app.git',
  clone_url: 'https://github.com/zyderus/movie-app.git',
  svn_url: 'https://github.com/zyderus/movie-app',
  homepage: 'https://watch-movies-app.herokuapp.com/',
  size: 1827,
  stargazers_count: 0,
  watchers_count: 0,
  language: 'JavaScript',
  has_issues: true,
  has_projects: true,
  has_downloads: true,
  has_wiki: true,
  has_pages: false,
  has_discussions: false,
  forks_count: 0,
  mirror_url: null,
  archived: false,
  disabled: false,
  open_issues_count: 0,
  license: null,
  allow_forking: true,
  is_template: false,
  web_commit_signoff_required: false,
  topics: ['feature'],
  visibility: 'public',
  forks: 0,
  open_issues: 0,
  watchers: 0,
  default_branch: 'main',
  permissions: {
    admin: true,
    maintain: true,
    push: true,
    triage: true,
    pull: true,
  },
};
